### PR TITLE
fixes gulp csslint error

### PR DESCRIPTION
**Pull request by VikramTiwari**
Temporary fix for: https://github.com/linnovate/mean/issues/1634

### CODE REVIEW

**Comment by pun4drunk** [comment]
May it be 'formatter' and not 'reporter'?
According to [usage example](https://github.com/lazd/gulp-csslint)

<code>
gulp.task('css', function() {
  gulp.src('client/css/*.css')
    .pipe(csslint())
    .pipe(csslint.formatter());
});
</code>

**Comment by VikramTiwari** [comment]
@pun4drunk Seems like it. It's working with `formatter`. All these linters are mess in themselves 💨

**Comment by pun4drunk** [comment]
If we fix it using 'formatter' I see a bunch of warnings from csslint, i.e. 
<code>
starter.css
28: warning at line 242, col 1
Rule doesn't have all its properties in alphabetical order.
.sprite-stackoverflow {
</code>

It makes sence if we look into .csslintrc, it has no <code>  "order-alphabetical": false,</code>
and I believe default value is true.

It should be fixed either sorting css properties or adjusting the csslint configuration. I would prefer first one for sure. Who's in charge for this?

**Comment by VikramTiwari** [comment]
@pun4drunk I think we can open a new issue for CSS cleanup and you can work on that. I will merge this PR into master and close the corresponding issue as well.

**Comment by divya0909** [comment]
Hi,
when I am working on  the Gulp test, I am facing error in csslint, So as per your code I  changed reporter to formatter, But facing the same issue.
Type Error : plugins.csslint.reporter is not a function.


gulp.task('csslint', function (done) {
  return gulp.src(defaultAssets.client.css)
    .pipe(plugins.csslint('.csslintrc'))
    .pipe(plugins.csslint.formatter())
    .pipe(plugins.csslint.formatter(function (file) {
      if (!file.csslint.errorCount) {
        done();
      }
    }));
});

**Pull request merged**
