### PR TITLE
Add docker-compose.yml

### PR DESCRIPTION
**Pull request by lvarayut**
This will help setting up the docker easier by using `docker-compose up`

### CODE REVIEW

**Comment by timelf123** [comment]
> Compose is a tool for defining and running multi-container Docker applications. With Compose, you use a Compose file to configure your application’s services. Then, using a single command, you create and start all the services from your configuration.

Steps to use:
1. Install [docker-compose](https://docs.docker.com/compose/install/)
2. docker-compose up
3. profit

**Comment by lvarayut** [comment]
@VikramTiwari Could you please review this PR? IMHO, it'll help people setting up the project easier.

**Comment by VikramTiwari** [comment]
:+1: @lvarayut

**Comment by liorkesos** [comment]
+1
I know it was merged but I'll play with it as well.
Good step.
Lior

On Mon, Jan 4, 2016 at 7:44 PM, Vikram <notifications@github.com> wrote:

> [image: :+1:] @lvarayut <https://github.com/lvarayut>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/pull/1397#issuecomment-168748856>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Pull request merged**
