### PR TITLE
add SEO support for html5 push state (using phantomjs) and implement html5 mode

### LINKED ISSUE #1027: Pretty URLs shipped standard
I slightly modified the mean package, as you can see [here](https://github.com/zwhitchcox/mean/tree/pretty-urls) to remove the #! prefix. I'm just trying to get a feel if anyone thinks this should be included in the standard package.

The key change is right [here](https://github.com/zwhitchcox/mean/blob/pretty-urls/config/express.js#L116). Instead of excluding every possible path not needed, as suggested in [this article](http://blog.inzite.io/how-to-remove-hashbang-for-single-page-meanio-web-app/), which, I think results in much simpler, cleaner, easier to use code, but, of course, I could be wrong.

You can see an example of how to include a path in the [articles package](https://github.com/zwhitchcox/mean/blob/pretty-urls/packages/articles/server/routes/articles.js#L14)

You can download this and use it right now, and everything should work. Please let me know what you think! If there is interest, I will submit a pull request. You'll have to checkout the pretty-urls branch

### PR DESCRIPTION
**Pull request by zwhitchcox**
This pr enables google to index your website, even if you are using html5 mode.

The line 
```js
  <meta name="fragment" content="!">
```

tells the crawler that this page is in html5 mode, and the crawler sends another request, appending ```?_escaped_fragment_=``` to the end of the url.

So, instead of the query
```
http:///localhost:3000
```
it would send the query
```
http:///localhost:3000?_escaped_fragment_
```

Since Google does not execute javascript, phantomjs will intercept all traffic with ```?_escaped_fragment_=``` in the url, render this code in html, and send the pure html in addition to the javascript.

fixes #1027

P.S.
I also added ```<base href='/'``` to ```head.html``` and changed ```hashPrefix('!')``` to ```html5Mode(true)```, both of which changes tell angular not to use the ```#!``` prefix.

### CODE REVIEW

**Comment by liorkesos** [comment]
Hi @zwhitchcox @pratik60  I'd like to integrate this as a key feature in 0.5
Can you resubmit the PR in a way that will pass the tests?
I will probably merge it to a 0.5 branch and invite you guys to help me push me out of the door...

**Comment by zwhitchcox** [comment]
All tests are now passing

**Comment by liorkesos** [comment]
Just merged it to 0.5 and tested it - works very nicely.
Defintly a sep forward for mean.

**Comment by zwhitchcox** [comment]
So glad I could help the project! Thank you very much

**Comment by liorkesos** [comment]
Hi @zlokomatic - Logging out does not seem to work for me.
Maybe some sort of collision?

**Comment by zwhitchcox** [comment]
Sorry about that! Should be working now

**Comment by liorkesos** [comment]
Cool. Working on making it coexist with our swagger pr... 0.5 is going to
be awesome.
Lior

**Comment by zwhitchcox** [comment]
woot woot

**Comment by zwhitchcox** [comment]
Just added coffeescript #1192

**Comment by timelf123** [comment]
@zwhitchcox @liorkesos what happened with this PR?

**Pull request closed without merging**
