### PR TITLE
Adding Cluster support for mean, running several workers based on amount of machine CPU

### PR DESCRIPTION
**Pull request by EyalFingold**
Adding Cluster support for mean, running several workers based on amount of machine CPU

Adding auto header to respond with the workerID

### CODE REVIEW

**Comment by gigenthomas** [comment]
Can you please provide some documentation on how to set up multiple nodes ?

**Comment by liorkesos** [comment]
just run node server.js instead of grunt.
Lior

On Fri, Jan 16, 2015 at 6:30 AM, Gigen Thomas <notifications@github.com>
wrote:

> Can you please provide some documentation on how to set up multiple nodes ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/pull/937#issuecomment-70207001>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by gigenthomas** [comment]
Does it share the same port ? and assuming it creates one worker per CPU ?

**Comment by EyalFingold** [comment]
Hi,

Yes, all workers share the same port, and its per CPU

Eyal


Sent from my iPhone; Please pardon roughness & spelling.

On Jan 16, 2015, at 09:38, Gigen Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


Does it share the same port ? and assuming it creates one worker per CPU ?

**Pull request merged**
