### PR TITLE
Gulp update

### PR DESCRIPTION
**Pull request by pashist**
- Removed webpack task. Instead used `webpack-dev-middleware`. It enabled nice [hot module replacement](http://webpack.github.io/docs/hot-module-replacement) feature of webpack. Also hope it reduced rebuilding time.
- Removed `less` and `sass` tasks. Instead used `less-loader` and `sass-loader` for webpack with  sourcemaps. Now `.less` and `.scss` files can be imported in packages.
- Fixed page reloading in `nodemon`.

### CODE REVIEW

**Comment by liorkesos** [comment]
Nice!
+1

**Comment by timelf123** [comment]
This is awesome, nice work. Testing now

**Comment by rjVapes** [comment]
@pashist With these changes, what are the paths of execution when js/css change?  My concern is that there's a webpack-dev path going off triggered by changes and a nodemon task executing from the same changes, racing towards a livereload which may happen before or after webpack is built (and if I'm reading the webpack-dev stuff the nodemon restart isn't actually necessary in this case).

**Comment by pashist** [comment]
@rjVapes basically files handled by webpack should not intersect with nodemon watched files, in nodemon config they are added to ignore section: 
```
ignore: [
        'node_modules/',
        'bower_components/',
        'bundle/',
        '../app.js',                           // handled by webpack
        'logs/',
        'packages/**/public/',   // <--- here handled by webpack too
        '.DS_Store', '**/.DS_Store',
        '.bower-*',
        '**/.bower-*',
        '**/tests'
      ],
```
Even if same file will watched by webpack and nodemon, after changes triggered, nodemon will restart server.js with webpack-dev-middleware inside, so any webpack building process will interrupt and executed again after server.js start

**Comment by liorkesos** [comment]
Great job Pavel.
Lior

**Comment by timelf123** [comment]
One minor fix webpack.test.js to make SASS and svg etc work:

```
'use strict'

module.exports = {
  module: {
    loaders: [{
      test: /\.css$/,
      loader: 'style-loader!css-loader'
    },{
      test: /\.scss$/,
      loaders: ['style', 'css?sourceMap', 'sass?sourceMap']
    }, {
      test: /\.js$/,
      exclude: /(node_modules|bower_components|lib)/,
      loader: 'babel?presets[]=es2015&presets[]=stage-1'
    }, {
      test: /\.(png|woff|woff2|eot|ttf|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: 'url'
    }]
  },
  resolve: {
    modulesDirectories: ['bower_components', 'node_modules']
  }
}
```

Other than that this looks good and I merged to my fork already, thanks again

**Comment by pashist** [comment]
Regarding  https://github.com/linnovate/mean/pull/1696/commits/26962b961f00a56975888567ef1a7b64293b8012. Since webpack-dev-middleware is an express server middleware, it will recompile bundle every time when nodemon restarts server due to server files changes. It's no problem if we currently develop public part. But if it's server part development, recompiling public files is unnecessary and `--no-wdm` option allow avoid this. With `--no-wdm` option public files changes will be tracked and bundle will rebuilded, just without HMR support. Webpack task used `webpack-stream` and watch mode, so recompiling time should be ok.
How you think is this useful ? And perhaps we should use this option as default ?

@rjVapes perhaps we could just disable files `.html` files caching in dev env ?

**Comment by timelf123** [comment]
@pashist So the issue is when nodemon restarts the process containing the webpack middleware, it loses the bundle information stored in memory, right?

Two workarounds if you want to reload the server component, either[ use a separate process for webpack middleware](https://gist.github.com/timelf123/98e93fb05f93b82a7fc472216a542eeb), or find a way to [reload your server routes without restarting the whole process](https://github.com/glenjamin/ultimate-hot-reloading-example) (this is maybe for next milestone?, essentially use webpack to generate server bundle and `require(package.routes)` allowing server side HMR)

I'm good with a `--no-wdm option` as a fallback/default for now. Also `webpack --watch` is usually faster for me anyway and the only thing we can currently HMR anyway is stylesheets

**Comment by adskjohn** [comment]
@pashist Sounds like a good solution (disabling .html cache).  Any time lost from not having the small volume of server side html cached I'm sure would more than be made up by not having to reload the server.

**Comment by timelf123** [comment]
@pashist thoughts on rebasing and merging?

**Comment by timelf123** [comment]
@pashist @liorkesos can we get this merged?

**Pull request merged**
