### PR TITLE
Revamp of users package

### PR DESCRIPTION
**Pull request by MilosStanic**
Everything is described here https://github.com/linnovate/mean/wiki/Revamp-of-users-package

### CODE REVIEW

**Comment by liorkesos** [comment]
Looks that you should also fix the tests regarding the users to adapt to this change.

**Comment by liorkesos** [comment]
@oritpersik  Can you review this?

**Comment by MilosStanic** [comment]
Hi guys, 

If you've already merged my jwt-auth branch, then there's no need in merging this. All this is contained in the jwt-auth pull request.

**Comment by liorkesos** [comment]
Please close the pr

**Comment by MilosStanic** [comment]
Already merged in jwt-auth PR

**Pull request closed without merging**
