### PR TITLE
Enable gzip on bower_components

### PR DESCRIPTION
**Pull request by pratik60**
This will enable gzip on bower_components and hence improve performance.

Fixes Issue => https://github.com/linnovate/mean/issues/753

### CODE REVIEW

**Comment by liorkesos** [comment]
I get express not defined error.
Steps to reproduce...
1.  mean init && npm install
2. ``` ReferenceError: express is not defined
    at module.exports (/Users/liorkesos/work/mean/prs/controllerAs/config/express.js:44:32)
    at Object.func (/Users/liorkesos/work/mean/prs/controllerAs/node_modules/meanio/lib/bootstrap.js:20:41)
    at get (/Users/liorkesos/work/mean/prs/controllerAs/node_modules/dependable/index.js:127:31)
    at /Users/liorkesos/work/mean/prs/controllerAs/node_modules/dependable/index.js:124:18
    at Array.map (native)
    at Meanio.get (/Users/liorkesos/work/mean/prs/controllerAs/node_modules/dependable/index.js:120:39)
    at enableModules (/Users/liorkesos/work/mean/prs/controllerAs/node_modules/meanio/lib/module.js:94:24)
    at findModulesDone (/Users/liorkesos/work/mean/prs/controllerAs/node_modules/meanio/lib/module.js:19:5)
    at _fulfilled (/Users/liorkesos/work/mean/prs/controllerAs/node_modules/meanio/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/Users/liorkesos/work/mean/prs/controllerAs/node_modules/meanio/node_modules/q/q.js:823:30)
```
3. ```git checkout -b pratik60-master master```
4. ``````

**Comment by pratik60** [comment]
Updated, thanks for the spot :-)

**Comment by pratik60** [comment]
@Lior - Could we merge this? Are you still having problems if you merge this?

**Comment by liorkesos** [comment]
Can you merge master on to you're PR?
travis fails with issues I think where addressed in the master..
Please see what the failures are about

**Pull request closed without merging**
