### PR TITLE
Changed config files to use the new db config object

### PR DESCRIPTION
**Pull request by thomastaylor312**
This is the change we mentioned in #737

### CODE REVIEW

**Comment by liorkesos** [comment]
@thomastaylor312 I know this is prehistoric - but I still the logic,
Can you resubmit against a recent mean instanace and sign the clahub so the tests pass?

**Comment by thomastaylor312** [comment]
@liorkesos The clahub isn't working for me at all. And just to clarify, do you need me to create a new PR against a newer version of mean or just update this one?

**Comment by liorkesos** [comment]
A lot of time has passed, please try to create one agains a new version
(best would be against an 0.5 branch checkout)
Lior

On Sun, May 3, 2015 at 12:35 AM, Taylor Thomas <notifications@github.com>
wrote:

> @liorkesos <https://github.com/liorkesos> The clahub isn't working for me
> at all. And just to clarify, do you need me to create a new PR against a
> newer version of mean or just update this one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/pull/749#issuecomment-98406741>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by thomastaylor312** [comment]
@liorkesos If you want me to keep the same syntax, I'll have to modify mean-cli as well. Is that what you wanted?

**Comment by liorkesos** [comment]
Yes I'd be happy to review that change in mean-cli as well...
If I understand the main motivation is the ability to specify some more
parameters to the db.
Another thing to attempt is to add a "type" paramater and thus open the
option for additional dbs (redis?, couch?) in the future...
Lior

On Sun, May 3, 2015 at 8:30 AM, Taylor Thomas <notifications@github.com>
wrote:

> @liorkesos <https://github.com/liorkesos> If you want me to keep the same
> syntax, I'll have to modify mean-cli as well. Is that what you wanted?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/pull/749#issuecomment-98438485>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by thomastaylor312** [comment]
@liorkesos Ok, I will be really busy this week, but I should be able to do it by next week. I'll add a `type` param that will do nothing for now, but that we can implement later in mean-cli.

**Comment by liorkesos** [comment]
Cool, thanks for helping out!
Lior

On Sun, May 3, 2015 at 8:40 AM, Taylor Thomas <notifications@github.com>
wrote:

> @liorkesos <https://github.com/liorkesos> Ok, I will be really busy this
> week, but I should be able to do it by next week. I'll add a type param
> that will do nothing for now, but that we can implement later in mean-cli.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/pull/749#issuecomment-98439779>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Pull request closed without merging**
