### PR TITLE
Made the mean project compatible with heroku deploy and mongolabs

### PR DESCRIPTION
**Pull request by peterhendrick**
I've added the proper dependencies to the package.json, and updated the shrinkwrap to reflect those changes.

I also added a gulptask, in case anyone is trying to use a heroku gulp buildpack.

Then I changed the config/env/all.js and config/env/production.js to point to mongolab.

Lastly, I added some known problems in karma to the .slugignore, in order to deploy properly.

This version should successfully deploy to a heroku instance using mongolab. There are still memory issues, since heroku's free memory dyno is only 512MB, and linnovate/mean uses more than that.

### CODE REVIEW

**Comment by liorkesos** [comment]
This is great,
I want to somehow generalise the mongo connection string stuff to be set in another part of config.
So if someone is using compose.io or a different mongo provider it will be clear where to set it.
Please see if you can use a MONGO_URI that will be set either by process.env.MONGOLAB_URI or any other...

**Comment by liorkesos** [comment]
@peterhendrick - Do you want to try to generalize this a little bit?
I'd be glad to merge but don't want to continue to hardcode to one dbaas provider.

**Comment by rjVapes** [comment]
@liorkesos @peterhendrick A large part of this is outdated since we no longer use gulp in production.  If the the method of determining the mongo uri needs to be more generic to support heroku then we should probably create and issue for that specifically and solve it.

**Comment by rjVapes** [comment]
Closing due to being outdated.  There are also some problems with the package.json changed proposed in this PR (duplicate dependencies in deps and devdeps, and removal of testing etc)

**Comment by peterhendrick** [comment]
No problem guys. This is outdated. When we originally made this request, these were the changes that we had identified to get it working on heroku. There's probably unnecessary changes in here. If your master branch still doesn't deploy to heroku out of the box, I can take a look at it and see how to fix it the right way. I have a much better understanding of what's going on now then I did when I made this request.

**Pull request closed without merging**
