### PR TITLE
moved bootstrap from head to assets as dependency

### PR DESCRIPTION
**Pull request by VikramTiwari**
moving towards css frameworks as packages

### CODE REVIEW

**Comment by emps** [comment]
this can make problems with bootstrap fonts

**Comment by VikramTiwari** [comment]
@emps Okay! But didn't understood why would it?

**Comment by shailendramonu** [comment]
No font icons will be loaded after this change. Check on console...

On Saturday, 1 August 2015, Karol <notifications@github.com> wrote:

> this can make problems with bootstrap fonts
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/pull/1290#issuecomment-126840243>.
>


-- 
Thanks & Regards,
Shailendra Singh

**Comment by emps** [comment]
@VikramTiwari cause all scripts in production mode gonna be at bower_components/build/* where will be missing fonts icons... bootstrap looking for his fonts in his original folder

**Comment by liorkesos** [comment]
@emps is right that is why we can now base it on the configuration - Made some preparations for this here - https://github.com/linnovate/mean/commit/96c06a556665a5210cd8e5d4f97de2f4a78915e9

**Comment by liorkesos** [comment]
closing this

**Pull request closed without merging**
