### PR TITLE
loading user from the db

### PR DESCRIPTION
**Pull request by emps**
loading user from db for every $http.get('/api/users/me') instead taking
the one that set on jwt, while refreshing the page created 'MeanUser'
(angular factory) that calls /api/users/me and on success setting
this.user that is MeanUser.user with the db loaded user we sending from
the server

### CODE REVIEW

**Comment by liorkesos** [comment]
Don't you think we  should do this just after the login? 
A query per page reload isn't necessarily what we want to do if we don't have to..

**Comment by emps** [comment]
the way how it is working now in mean 0.5 is 
user login > auth with passportjs sets req.user that sent payload to the client. 
and now server can know who is his client only by the token and not using any more passport js to set req.user its just taking the payload from the token and sets back to the req.user after confirming that the token is valid ye.
in this way req.user stays same from the login moment and not get updated from the db any more.
what i suggest is load user from the db.. even better todo it for any api request that will cover any get *

**Comment by liorkesos** [comment]
That is not very performant,
What is the problem your trying to solve?
Lior

On Sun, Jun 7, 2015 at 4:39 PM, Karol <notifications@github.com> wrote:

> the way how it is working now in mean 0.5 is
> user login > auth with passportjs sets req.user that sent payload to the
> client.
> and now server can know who is his client only by the token and not using
> any more passport js to set req.user its just taking the payload from the
> token and sets back to the req.user after confirming that the token is
> valid ye.
> in this way req.user stays same from the login moment and not get updated
> from the db any more.
> what i suggest is load user from the db.. even better todo it for any api
> request that will cover any get *
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/pull/1204#issuecomment-109758045>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by emps** [comment]
u can see it if u login as admin and just go to users managment rename fields refresh ur page u say with old name

**Comment by emps** [comment]
i can explain it more in the phone..

**Comment by rjVapes** [comment]
The middle ground might be to compare a sort of lastUpdate field on the user.  Checking to see if a single field is out of sync, then reloading the user if so, instead of pulling the entire user on every page load.

**Comment by emps** [comment]
i leave this for mean team to fix untill then im fine with this one

**Comment by emps** [comment]
fix can come from express-jwt side that will load up to date user and set in req.user and not from jwt

**Comment by rjVapes** [comment]
This has been resolved in master.

**Pull request closed without merging**
