### PR TITLE
cleaning up commented if() and disabling 'trust proxy' in express

### PR DESCRIPTION
**Pull request by lirantal**
removing commented if() which is obsolete and express configuration to enable trust proxy support which will allow attackers to spoof their IPs and logs will be unable to reveal that

### CODE REVIEW

**Comment by liorkesos** [comment]
@zohar - I'm going to merge @lirantal (welcome back!) PR and we'll assess how valuable/accurate the ip info.
We will decide together and try to see if there is an alternate way to gain the ip info but if there is a security concern here I'd rather address it first and then add functionality or visibility.

**Comment by lirantal** [comment]
@liorkesos I never left :-)

**Comment by VikramTiwari** [comment]
Is the security issue related to DDOS attack? Seems me and @zohar are somehow missing that obvious elephant.

**Comment by lirantal** [comment]
How about you re-read http://expressjs.com/guide/behind-proxies.html and see if it makes sense to you. Maybe I'm just generating an elephant in my mind :)

**Comment by VikramTiwari** [comment]
hahaha this helps. :)

Thanks and Regards!
____________
Vikram Tiwari <https://google.com/+VikramTiwari>
Google Developers Group
<https://developers.google.com/groups/chapter/114576537688641864561/>
New Delhi, +91-9953414489

**Comment by zohar** [comment]
@lirantal @liorkesos I still don't consider it as a very high security risk, since we're only talking of logs, and it would be a mistake to use IP in logs to identify a real attacker. 
In any case - I would also prefer to see this in an environment configuration rather than in the general express.js. And probably using `app.set('trust proxy', 'loopback')` is better, so we're only trusting our localhost (which is usually the proxy).

Also - regarding the "most of mean.io users not using proxy" - this might be true for development environments. I'm not at all sure it's true for production environments where several apps are running simultaneously and in conjunction with other non-mean apps.

**Pull request merged**
