### PR TITLE
Bugfix/1264 twitter express session

### PR DESCRIPTION
**Pull request by dazwin**
In addition to requiring express-session, Twitter OAuth is silently failing because mean is requiring an email address. This PR gets Twitter logins working out-of-the-box (except for configuring consumer, keys of course) by change email to a non-required field in Mongoose. Clearly, this has a wider impact but I believe it's benign, and the 'right thing' to do.

One other thing to note - when I run npm shrinkwrap, all the 'from' attributes are updated to use a different format. I assume this is a change in npm behavior (I'm using the latest version - 2.13.0). For the purposes of this PR, I've only committed the hunk that is required.

### CODE REVIEW

**Comment by liorkesos** [comment]
Note that we have trasnfered to use jwt which is essentially sessionless.
I don't think I'll accept this PR - but I would love if you can check and try to implement the twitter integration based on jwt.
heres a link for reference...
http://blog.matoski.com/articles/jwt-express-node-mongoose/

**Comment by rjVapes** [comment]
@dazwin As @liorkesos mentioned we don't use sessions, so we'd need a JWT approach.  If you intend to update this by going that route that would be awesome.  If not, could you create an issue and reference/close this PR?

**Comment by dazwin** [comment]
I have a new project that needs LinkedIn and Google OAuth. If it doesn't take too long, I'll implement this with JWT.

Referencing my original bug on the issue: https://github.com/linnovate/mean/issues/1264

**Comment by rjVapes** [comment]
Perfect, thanks.  Going to close the PR, but hopefully we'll get it sorted in JWT fashion.

**Pull request closed without merging**
